#!/usr/bin/env python3

import colors as c
import random

score = 0

print(c.red+'''
Welcome to the quiz game.
'''+c.reset)

def q1():
    print("What is the capital of North Carolina?")
    answer = input('> ').strip().lower()
    if answer == "durham":
        print("Nope, but close, literally")
        return 2
    elif answer == "raleigh":
        print("YES!!")
        return 10
    else:
        print("Nope.")
        return 0 

def q2():
    print("What is the capital of Utah?")
    answer = input('> ').strip().lower()
    if 'salt lake' in answer:
        print("YES!!")
        return 10
    else:
        print("Nope.")
        return 0 

def q3():
    print("What is the capital of Assyria?")
    answer = input('> ').strip().lower()
    if answer == "assur":
        print("YES!!")
        return 10
    else:
        print("Nope.")
        return 0 

questions = [q1,q2,q3]

while questions:
    question = random.choice(questions)
    points = question()
    score += points
    if points:
        questions.remove(question)

print("Congratulations, score: ", score)





