#!/usr/bin/env python3

import colors as c
import random
import questions as q

score = 0

print(c.red+'''
Welcome to the quiz game.
'''+c.reset)

questions = q.questions

while questions:
    question = random.choice(questions)
    points = question()
    score += points
    if points:
        questions.remove(question)

print("Congradulations, score: ", score)





