#!/usr/bin/env node

'use strict';

var c = require('skilstak-colors');

// this works but really browser-ish
// console.log("Hello world");
// let's use a stream instead ...

var out = process.stdout;

while (true) {
  out.write(c.clear + c.rc() + "Hello " + c.rc() + "world\n" + c.x);
}
