#!/usr/bin/env node

'use strict';

var c = require("skilstak-colors");

// too browser-ish
//console.log("Hello world");

var out = process.stdout;

// clear the screen by writing the specials clear color
out.write(c.cl);

while (true) {
  out.write(c.rc() + "Hello world " + c.x);
}

