#!/usr/bin/env python3

import colors as c
import random

print(c.clear)
print(c.red + '''
Welcome to the magic eight ball!
Enter your question below.
''' + c.reset)

answers = [
    c.green + 'Yes.' + c.reset,
    c.red + 'No.' + c.reset,
    c.base01 + 'Maybe.' + c.reset
]

question = input('> ' + c.yellow)
answer = random.choice(answers)
print(answer)
