#!/usr/bin/env python3

import colors as c
import sys

print(c.clear + c.red + 'Mmmmmmmmmultiplication tables' + c.reset)

if len(sys.argv) < 2:
    number = input('Please enter a number: ')
else:
    number = sys.argv[1] 

print('1 x', number, '=', number * 1)
print('2 x', number, '=', number * 2)
