#!/usr/bin/env python3

import colors as c

print(c.clear + c.yellow + "Do you like waffles?" + c.reset)
answer = input("> ")

if answer == "yes":
    print("Awesome")
else:
    print("Well I like waffles.")

