#!/usr/bin/env python3 

import time
import colors as c
import math

started = time.time()
seconds_in_week = 604800
seconds_in_day = 86400
seconds_in_hour = 3600
seconds_in_minute = 60

def show():
    elapsed = time.time() - started 
    weeks = math.floor(elapsed / seconds_in_week)
    remainder = elapsed % seconds_in_week
    days = math.floor(remainder / seconds_in_day)
    remainder = remainder % seconds_in_day
    hours = math.floor(remainder / seconds_in_hour)
    remainder = remainder % seconds_in_hour
    minutes = math.floor(remainder / seconds_in_minute)
    seconds = remainder % seconds_in_minute
    print(c.clear, end='')
    print(c.yellow + 'weeks: ' + c.reset)
    print(weeks)
    print(c.yellow + 'days: ' + c.reset)
    print(days)
    print(c.yellow + 'hours: ' + c.reset)
    print(hours)
    print(c.yellow + 'minutes: ' + c.reset)
    print(minutes)
    print(c.yellow + 'seconds: ' + c.reset)
    print(seconds)

try:
    while True:
        show()
        time.sleep(0.01)
except KeyboardInterrupt:
    print("\b\b\b")
    exit()
