#!/usr/bin/env python3 

import time
import colors as c

weeks = 0
days = 0
hours = 0
minutes = 0
seconds = 0
hundredths = 0

def show():
    print(c.clear, end='')
    print(c.yellow + 'weeks: ' + c.reset)
    print(weeks)
    print(c.yellow + 'days: ' + c.reset)
    print(days)
    print(c.yellow + 'hours: ' + c.reset)
    print(hours)
    print(c.yellow + 'minutes: ' + c.reset)
    print(minutes)
    print(c.yellow + 'seconds: ' + c.reset)
    print(seconds)
    print(c.yellow + 'hundredths: ' + c.reset)
    print(hundredths)

try:
    while True:
        show()
        time.sleep(0.01)
        hundredths += 1
        if hundredths == 100:
            seconds += 1
            hundredths = 0
        if seconds == 60:
            minutes += 1
            seconds = 0
        if minutes == 60:
            hours += 1
            minutes = 0
        if hours == 24:
            days += 1
            hours = 0
        if days == 7:
            weeks += 1
            days = 0
except KeyboardInterrupt:
    print("\b\b\b")
    exit()
