#!/usr/bin/env python3 

import time
import colors as c
import math

def since(started):
    elapsed = time.time() - started 
    weeks = math.floor(elapsed / 604800)         # seconds in week
    remainder = elapsed % 604800
    days = math.floor(remainder / 86400)         # seconds in day
    remainder = remainder % 86400
    hours = math.floor(remainder / 3600)         # seconds in hour
    remainder = remainder % 3600
    minutes = math.floor(remainder / 60)         # seconds in minute
    seconds = remainder % 60
    return (seconds,minutes,hours,days,weeks)

def show_since(started,form='{}w {}d {}:{:02}:{:05.2f}'):
    (seconds,minutes,hours,days,weeks) = since(started)
    print(c.clear + form.format(weeks,days,hours,minutes,seconds))

try:
    began = time.time()
    while True:
        show_since(began)
        time.sleep(0.01)
except KeyboardInterrupt:
    show_since(began,'{} weeks\n{} days\n{} hours\n{} minutes\n{} seconds')
    exit()
