#!/usr/bin/env python3

import colors as c
print(c.clear)

sides = ["1","2","3","4","5","6"]

print("side ",sides[0])
print("side ",sides[1])
print("side ",sides[2])
print("side ",sides[3])
print("side ",sides[4])
print("side ",sides[5])
#print("side ",sides[6]) # WRONG
