#!/usr/bin/env python3

import skilstak.colors as c
import random
import os 
import json
import re

def ask(prompt):
    """Prompt the user to type input.
    
    Args:
        prompt (str): Text to use as user prompt

    Returns: 
        str: Typed in text stipped of whitespace and lowercase

    """
    answer = input(prompt).strip().lower()
    return answer

def load_answers(path):
    """Loads answers from answers.json and from ascii"""
    data = path + "/answers.json"
    txt    = path + "/ascii"
    answers = []
    with open(data) as f:
        answers = json.load(f);
    for name in os.listdir(txt):
        if name.endswith(".txt") and not (name == "welcome.txt" or name == "bye.txt"):
            with open(txt + "/" + name) as f:
                one = f.read()
                answers.append(one)
    return answers

def load_responses(path):
    """Loads response from responses.json and from ascii/responses"""
    data = path + "/responses.json"
    txt = path + "/ascii/responses"
    responses = []
    with open(data) as f:
        responses = json.load(f);
    for r in responses:
        regx = r[0]
        special = r[1]
        if special.endswith(".txt"):
            fname = txt + "/" + special
            with open(fname) as s:
                buf = s.read()
                r[1] = buf
    return responses

def has_special_response(question,responses):
    """See if question matches the any of the special response questions."""
    for r in responses:
        regx = r[0]
        if re.search(regx,question):
            return r[1]

def welcome(data):
    txt = data + "/ascii/welcome.txt"
    if os.path.isfile(txt):
        with open(txt) as f:
            welcome_message = f.read()
    print(c.clear + c.rc() + welcome_message + c.reset)

def bye(data):
    goodbye = "Goodbye. Come back soon!"
    txt = data + "/ascii/bye.txt"
    if os.path.isfile(txt):
        with open(txt) as f:
            goodbye = f.read()
    print(goodbye)
    exit()

def answer_question(answers,responses,data):
    """Prompt for a single question and answer it."""
    question = ask("--> " + c.b3)
    print(c.reset, end='')
    if question == 'bye' or question == 'goodbye':
        bye(data)
    special = has_special_response(question,responses)
    if special:
        answer = special
    else:
        answer = random.choice(answers)
    print(c.random() + answer + c.x)

def eightball(answers,responses,data):
    """Main eightball loop. Ask and answer questions, forever."""
    try:
        while True:
            answer_question(answers,responses,data)
    except KeyboardInterrupt:
        print()
        bye(data)

if __name__ == '__main__':
    data = os.environ["FUNDATA"] + "/eightball"
    welcome(data)
    answers = load_answers(data)
    responses = load_responses(data)
    eightball(answers,responses,data)

