#!/usr/bin/env python3

import skilstak.colors as c
import random
import os 
import json
import re

def load_answers(path):
    """Loads answers from answers.json and from ascii"""
    json_file = path + "/eightball/answers.json"
    txt_files = path + "/eightball/ascii"
    answers = []
    with open(json_file) as f:
        answers = json.load(f);
    for name in os.listdir(txt_files):
        if name.endswith(".txt"):
            with open(txt_files + "/" + name) as f:
                one = f.read()
                answers.append(one)
    return answers

def welcome():
    welcome_message = '''
Welcome to the magic eight ball!
Enter your question below.
'''
    txt = os.environ["FUNDATA"] + "/eightball/ascii/welcome.txt"
    if os.path.isfile(txt):
        with open(txt) as f:
            welcome_message = f.read()

    print(c.clear + c.rc() + welcome_message + c.reset)

def ask(prompt):
    answer = input(prompt).strip().lower()
    return answer

def bye():
    goodbye = "Goodbye. Come back soon!"
    txt = os.environ["FUNDATA"] + "/eightball/ascii/bye.txt"
    if os.path.isfile(txt):
        with open(txt) as f:
            goodbye = f.read()
    print(goodbye)
    exit()

def get_special_response(question):
    with open(os.environ["FUNDATA"] + "/eightball/responses.json") as f:
        responses = json.load(f)
        for r in responses:
            regx = r[0]
            special_response = r[1]
            if re.search(regx,question):
                return special_response

def handle_question(answers):
    question = ask("--> " + c.b3)
    print(c.reset, end='')
    if question == 'bye' or question == 'goodbye':
        bye()
    special = get_special_response(question)
    if special:
        answer = special
    else:
        answer = random.choice(answers)
    print(c.random() + answer + c.x)


if __name__ == '__main__':
    try: 
        welcome()
        answers = load_answers(os.environ["FUNDATA"])
        while True:
            handle_question(answers)
    except KeyboardInterrupt:
        print()
        bye()
