#!/usr/bin/env python3

"""Not yo grandma's hello world."""

import skilstak.colors as c
import time

def plain(message):
    """Clears the screen and prints 'Hello world'."""
    print(c.clear + c.rc() + message + c.reset)

def multi(message):
    """Prints 'Hello world' in multiple colors like a Christmas tree (or Vegas sign)."""
    while True:
        print(c.clear + c.multi(message))
        time.sleep(0.5)

def color(message):
    """Fills the screen with randomly colored 'Hello world's."""
    print(c.clear)
    while True:
        print(c.rc() + message + c.reset, end=" ")

def hello(kind='plain',message='Hello world!'):
    """Main 'Hello world' function"""
    try:
        if kind == 'color':
            color(message)
        elif kind.startswith('m'):
            multi(message)
        else:
            plain(message)
    except KeyboardInterrupt:
        return

if __name__ == '__main__':
    import sys
    if len(sys.argv) == 1:
        hello()
    else:
        hello(sys.argv[1])
