#!/usr/bin/env python3

import skilstak.colors as c

try:
    print(c.clear)
    while True:
        print(c.rc() + "Hello " + c.rc() + "world" + "!" + c.x, end=" ") 
except KeyboardInterrupt:
    exit()

