#!/usr/bin/env python3

import random

sides = []

sides.append("1")
sides.append("2")
sides.append("3")
sides.append("4")
sides.append("5")
sides.append("6")

while True:
    side = random.choice(sides)
    print("rolled: " + side, end='')
    input()

##############################
# Keep for reference later:
#
# for side in sides:
#     print("no index needed for", side)
#
# for n in range(6):
#     print("index", n, "is side", sides[n])
#
# n = 0
# while n < 6:
#     print("index", n, "is side", sides[n])
#     n = n + 1
#
