#!/usr/bin/env python3 

import colors as c
import random
import time

try:
    while True:
        ending = ' ' * random.randint(1,20)
        print(c.rc() + 'Nyan' + c.x, end=ending)
except:

    try:

        print(c.cl)

        while True:

            print("\n\n\n")

            print(    
            c.r + ' - - - - - - - - - - - - - - - -' + c.magenta + ' ,------,\n' +
            c.o + '- - - - - - - - - - - - - - - - ' + c.magenta + '|       |\n' +
            c.y + ' - - - - - - - - - - - - - - - -' + c.magenta + '|    ' + c.base00 + '/\_/\\\n' +
            c.g + '- - - - - - - - - - - - - - - -' + c.base00 + '~' + c.magenta + "|___" + c.base00 + '(_^_.^)\n' +
            c.b + ' - - - - - - - - - - - - - - - -' + c.base00 + ' "  "\n' +
            c.v + '- - - - - - - - - - - - - - - - ')

            time.sleep(.25)
            print(c.cl)

            print('\n')
            print('\n')

            print(
            c.r + '- - - - - - - - - - - - - - - - ' + c.m + ' ,------,\n' +
            c.o + ' - - - - - - - - - - - - - - - -' + c.m + '|       |\n' +
            c.y + '- - - - - - - - - - - - - - - - ' + c.m + '|    ' + c.b00 + '/\_/\\\n' +
            c.g + '- - - - - - - - - - - - - - - -' + c.b00 + '~' + c.m + "|___" + c.b00 + '(_^_.^)\n' +
            c.b + '- - - - - - - - - - - - - - - - ' + c.b00 + '     "  "\n' +
            c.v + ' - - - - - - - - - - - - - - - -')

            time.sleep(.25)
            print(c.cl)

    except: 
        print(c.cl)
        exit(0)
