#!/usr/bin/env python3

import time
import RPi.GPIO as GPIO

pins = [5,6,13,19]
sleep = 1
count = 0

GPIO.setmode(GPIO.BCM)

for pin in pins:
    GPIO.setup(pin,GPIO.OUT)

while True:
    binstr = "{:04b}".format(count)
    last = len(binstr)
    last_four = binstr[last-4:last]
    for n in range(4):
        if bool(int(last_four[n])):
            GPIO.output(pins[n], GPIO.LOW)
        else:
            GPIO.output(pins[n] GPIO.HIGH)
    count += 1
    time.sleep(sleep)
