#!/usr/bin/env python3

import colors as c
from cli import ask

print(c.clear + c.magenta + '''
Welcome to the Pink Fluffy Unicorns quiz.
''')

answer = ask("What color are the unicorns?")
answer = ask("What are the unicorns dancing on?")
answer = ask("Use one word to describe the texture of their magical fur?")


