#!/usr/bin/env python3

import colors as c

print(c.red + '''
Welcome to the magic eight ball!
Enter your question below.
''' + c.reset)

answers = [
    c.green + 'Yes.' + c.reset,
    c.red + 'No.' + c.reset,
    c.base01 + 'Maybe.' + c.reset
]

print(c.clear)
print(c.random_color() + 'Answers:' +  c.reset)
print(answers)
print()

print(c.random_color() + 'Number of answers:' + c.reset)
print(len(answers))
print()

print(c.random_color() + 'The first answer is' + c.reset)
print(answers[0])
print()

print(c.random_color() + 'The last answer is' + c.reset)
print(answers[2])
print()
