#!/usr/bin/env python3 

import time
import colors as c

seconds = 0
hundredths = 0

while True:
    print(c.clear) 
    print(c.yellow + 'seconds: ' + c.reset)
    print(seconds)
    print(c.yellow + 'hundredths: ' + c.reset)
    print(hundredths)
    time.sleep(0.01)
    hundredths += 1
    if hundredths == 100:
        seconds += 1
        hundredths = 0
