#!/usr/bin/env python3 

import time
import colors as c

count = 0
print(c.clear)
print(c.cyan + '[Control-C to stop]' + c.reset, end=': ', flush=True)
print(count)

while True:
    time.sleep(1)
    count += 1
    print(c.clear)
    print(c.cyan + '[Control-C to stop]' + c.reset, end=': ', flush=True)
    print(count)
