#!/usr/bin/env python3 

import time
import colors as c

mesg = c.clear + c.cyan + '[Control-C to stop] ' + c.reset
form = '{}-{:02}:{:02}:{:02}.{:02}'

days = 0
hours = 0
minutes = 0
seconds = 0
hundredths = 0

while True:
    print( mesg + form.format(days,hours,minutes,seconds,hundredths))
    time.sleep(0.01)
    hundredths += 1
    if hundredths == 100:
        seconds += 1
        hundredths = 0
    if seconds == 60:
        minutes += 1
        seconds = 0
    if minutes == 60:
        hours += 1
        minutes = 0
    if hours == 24:
        days += 1
        hours = 0
