#!/usr/bin/env python3

import time
import colors as c

"""
This one is just for fun. It traps an exception called `KeyboardInterrupt`
when `<control>-c` is typed. We learn about exceptions much later,
but good to try one on for size now. Exceptions are 'thrown' when
something goes wrong and sometimes just to help communicate in complicated
code. Anything in the `try` block that throws an exception is caught and
compared to the list of exceptions named after `except`. If any matches
are found then the `except` loop executes, otherwise it just skips it.
"""

print(c.clear)
print(c.blue + '[Control-C to quit counting]')

seconds = 0

try:
    while True:
        print(c.yellow + str(seconds) + c.magenta + " seconds")
        time.sleep(1)
        seconds += 1   # this is called an 'increment' operator
except KeyboardInterrupt:
    print(c.blue + '\b\bBubye' + c.reset)
    exit()
