#!/usr/bin/env python3 

import time
import colors as c

count = 0
interval = 0.01

def show():
    print(c.clear)
    print(c.cyan + '[Control-C to stop]' + c.reset, end=': ', flush=True)
    print('{:.2f} seconds'.format(count))

#-----------------------------------------------------------------------

show()

try:
    while True:
        time.sleep(interval)
        count += interval 
        show()
except KeyboardInterrupt:
    show()
    exit()
