#!/usr/bin/env python3 

import time
import colors as c

hundredths = 0

while True:
    print(c.clear)
    print(c.cyan + '[Control-C to stop]' + c.reset, end=': ')
    print(hundredths)
    time.sleep(0.01)
    hundredths += 1
