#!/usr/bin/env python3 

import time
import colors as c

seconds = 0
hundredths = 0

while True:
    print(c.clear + c.cyan + '[Control-C to stop]' + c.reset, end=': ')
    print(seconds, end=':')
    print(hundredths)
    time.sleep(0.01)
    hundredths += 1
    if hundredths >= 100:
        hundredths = hundredths % 100
        seconds += 1
