#!/usr/bin/env python3 

import time
import colors as c

days = 0
hours = 0
minutes = 0
seconds = 0
hundredths = 0
mesg = c.clear + c.conceil + '\n' * 15 + c.cyan + '                             [Control-C to stop] ' + c.reset

while True:
    print(mesg + '{}-{}:{}:{}.{}'.format(days,hours,minutes,seconds,hundredths))
    time.sleep(0.01)
    hundredths += 1
    if hundredths == 100:
        seconds += 1
        hundredths = 0
    if seconds == 60:
        minutes += 1
        seconds = 0
    if minutes == 60:
        hours += 1
        minutes = 0
    if hours == 24:
        days += 1
        hours = 0
