#!/usr/bin/env python3 

import time
import colors as c
import math

short_form = c.base3 + '{}w {}d {}:{:02}:{:05.2f}' + c.reset

long_form =  c.red     + 'weeks:   ' + c.base3 + '{}\n'
long_form += c.orange  + 'days:    ' + c.base3 + '{}\n'
long_form += c.green   + 'hours:   ' + c.base3 + '{}\n'
long_form += c.blue    + 'minutes: ' + c.base3 + '{}\n'
long_form += c.magenta + 'seconds: ' + c.base3 + '{}\n'

def since(started):
    elapsed = time.time() - started 
    weeks = math.floor(elapsed / 604800)         # seconds in week
    remainder = elapsed % 604800
    days = math.floor(remainder / 86400)         # seconds in day
    remainder = remainder % 86400
    hours = math.floor(remainder / 3600)         # seconds in hour
    remainder = remainder % 3600
    minutes = math.floor(remainder / 60)         # seconds in minute
    seconds = remainder % 60
    return (seconds,minutes,hours,days,weeks)

def show_since(started,form=long_form):
    (seconds,minutes,hours,days,weeks) = since(started)
    print(c.clear + form.format(weeks,days,hours,minutes,seconds))

try:
    began = time.time()
    while True:
        show_since(began)
        time.sleep(0.01)
except KeyboardInterrupt:
    show_since(began,long_form)
    exit()
