#!/usr/bin/env python3

import time
import colors as c

count_length = 0.387

snake = '''
                 _        
                | |       
 ___ _ __   __ _| | _____ 
/ __| '_ \ / _` | |/ / _ \\
\__ \ | | | (_| |   <  __/
|___/_| |_|\__,_|_|\_\___|
                          
'''

while True:

    print(c.clear, end='')

    for verse in range(5):

        for n in range(12):
            print(c.yellow + 'Badger!' + c.reset)
            time.sleep(count_length)

        if verse < 4:
            for n in range(2):
                print(c.magenta + 'Mushroom.' + c.reset)
                time.sleep(count_length * 2)
        else:
            print(snake)
            time.sleep(count_length * 11)
        
        print(c.clear, end='')

