#!/usr/bin/env python3

import colors as c
import time

print(c.clear + c.yellow + "Hello " + c.blue + "world 1" + c.reset) 
time.sleep(1)
print(c.CLEAR + c.YELLOW + "Hello " + c.BLUE + "world 2" + c.RESET) 
time.sleep(1)
print(c.CL + c.Y + "Hello " + c.B + "world 3" + c.X) 
time.sleep(1)
print(c.cl + c.y + "Hello " + c.b + "world 4" + c.x) 
time.sleep(1)

while True:
    print(c.cl + c.random_color() + "Hello " + c.random_color() + "world" + c.x) 
    time.sleep(1)
    print(c.cl + c.rcolor() + "Hello " + c.rcolor() + "world" + c.x) 
    time.sleep(1)
    print(c.cl + c.rc() + "Hello " + c.rc() + "world" + c.x) 
    time.sleep(1)
